# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600a2b478fa4ca8370767b77c4827d4a5a2aee2d76cf7bad07fbea08421ab3a32ab20a228b8b31e9d9a3c5e00eedc5180250a261d193ddb3b0b90beeaf03358e

test:
  secret_key_base: 52a195552f2ca888070567e137cc7f6917486e337733fcb301bfecc905ad8657747305346dbc6c51f071301c077bc2b5d79291204ff74056973872e2801c9e68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
